server:
  port: 8002
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.bjc.cloud.entity                # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
    
spring:
   application:
    name: microservicecloud-dept 
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB02              # 数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

##  
#   下面的配置，通俗的讲可以这么理解：
# 8001,你要给我入驻到Eureka，入驻到哪个Eureka注册中心了，你得告诉我url与端口号吧，
# defaultZone就是用来指定入驻地址的配置，入驻到http://localhost:7001/eureka这个Eureka上
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/,http://eureka7003:7003/eureka/
  instance:
    instance-id: microservicecloud-dept8002   # 修改Eureka服务中心服务列表显示主机别名
    prefer-ip-address: true                   # 访问路径可以显示IP地址
    
info:
  app.name: zoudm-microservicecloud
  company.name: www.zoudmbean.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
 
 
 
 
