server: 
  port: 9527
 
spring: 
  application:
    name: microservicecloud-zuul-gateway
 
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/,http://eureka7003:7003/eureka/
  instance:
    instance-id: gateway-9527
    prefer-ip-address: true 

zuul: 
  ## ignored-services: microservicecloud-dept
  prefix: /zoudm
  ignored-services: "microservicecloud-*"
  routes: 
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**
 
 
info:
  app.name: zoudm-microservicecloud
  company.name: www.zoudmbean.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
